apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyin-sociality-dep
spec:
  selector:
    matchLabels:
      app: goyin-sociality
  replicas: 1
  template:
    metadata:
      labels:
        app: goyin-sociality
    spec:
      containers:
        - name: goyin-sociality
          image: violapioggia/goyin_sociality
          ports:
            - containerPort: 10002
          volumeMounts:
            - name: goyin-sociality-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: goyin-sociality-data
          hostPath:
            path: /home/violapioggia/goyin/sociality/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: goyin-sociality-svc
spec:
  ports:
    - name: goyin-sociality
      port: 10002
      targetPort: 10002
  selector:
    app: goyin-sociality
  type: ClusterIP