apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyin-api-dep
spec:
  selector:
    matchLabels:
      app: goyin-api
  replicas: 1
  template:
    metadata:
      labels:
        app: goyin-api
    spec:
      containers:
        - name: goyin-api
          image: violapioggia/goyin_api
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: goyin-api-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: goyin-api-data
          hostPath:
            path: /home/violapioggia/goyin/api/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: goyin-api-svc
spec:
  ports:
    - name: goyin-api
      port: 8080
      targetPort: 8080
      nodePort: 30090
  selector:
    app: goyin-api
  type: NodePort