apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyin-interaction-dep
spec:
  selector:
    matchLabels:
      app: goyin-interaction
  replicas: 1
  template:
    metadata:
      labels:
        app: goyin-interaction
    spec:
      containers:
        - name: goyin-interaction
          image: violapioggia/goyin_interaction
          ports:
            - containerPort: 10003
          volumeMounts:
            - name: goyin-interaction-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: goyin-interaction-data
          hostPath:
            path: /home/violapioggia/goyin/interaction/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: goyin-interaction-svc
spec:
  ports:
    - name: goyin-interaction
      port: 10003
      targetPort: 10003
  selector:
    app: goyin-interaction
  type: ClusterIP