apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenfish-user-dep
spec:
  selector:
    matchLabels:
      app: greenfish-user
  replicas: 1
  template:
    metadata:
      labels:
        app: greenfish-user
    spec:
      containers:
        - name: greenfish-user
          image: violapioggia/greenfish_user
          ports:
            - containerPort: 10001
          volumeMounts:
            - name: greenfish-user-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
          - name: greenfish-user-data
            hostPath:
              path: /home/violapioggia/greenfish/user/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: greenfish-user-svc
spec:
  ports:
    - name: greenfish-user
      port: 10001
      targetPort: 10001
  selector:
    app: greenfish-user
  type: ClusterIP