apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyin-chat-dep
spec:
  selector:
    matchLabels:
      app: goyin-chat
  replicas: 1
  template:
    metadata:
      labels:
        app: goyin-chat
    spec:
      containers:
        - name: goyin-chat
          image: violapioggia/goyin_chat
          ports:
            - containerPort: 10004
          volumeMounts:
            - name: goyin-chat-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: goyin-chat-data
          hostPath:
            path: /home/violapioggia/goyin/chat/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: goyin-chat-svc
spec:
  ports:
    - name: goyin-chat
      port: 10004
      targetPort: 10004
  selector:
    app: goyin-chat
  type: ClusterIP