apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyin-video-dep
spec:
  selector:
    matchLabels:
      app: goyin-video
  replicas: 1
  template:
    metadata:
      labels:
        app: goyin-video
    spec:
      containers:
        - name: goyin-video
          image: violapioggia/goyin_video
          ports:
            - containerPort: 10005
          volumeMounts:
            - name: goyin-video-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: goyin-video-data
          hostPath:
            path: /home/violapioggia/goyin/video/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: goyin-video-svc
spec:
  ports:
    - name: goyin-video
      port: 10005
      targetPort: 10005
  selector:
    app: goyin-video
  type: ClusterIP