apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenfish-video-dep
spec:
  selector:
    matchLabels:
      app: greenfish-video
  replicas: 1
  template:
    metadata:
      labels:
        app: greenfish-video
    spec:
      containers:
        - name: greenfish-video
          image: violapioggia/greenfish_video
          ports:
            - containerPort: 10005
          volumeMounts:
            - name: greenfish-video-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: greenfish-video-data
          hostPath:
            path: /home/violapioggia/greenfish/video/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: greenfish-video-svc
spec:
  ports:
    - name: greenfish-video
      port: 10005
      targetPort: 10005
  selector:
    app: greenfish-video
  type: ClusterIP