apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenfish-sociality-dep
spec:
  selector:
    matchLabels:
      app: greenfish-sociality
  replicas: 1
  template:
    metadata:
      labels:
        app: greenfish-sociality
    spec:
      containers:
        - name: greenfish-sociality
          image: violapioggia/greenfish_sociality
          ports:
            - containerPort: 10002
          volumeMounts:
            - name: greenfish-sociality-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: greenfish-sociality-data
          hostPath:
            path: /home/violapioggia/greenfish/sociality/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: greenfish-sociality-svc
spec:
  ports:
    - name: greenfish-sociality
      port: 10002
      targetPort: 10002
  selector:
    app: greenfish-sociality
  type: ClusterIP