// Code generated by Kitex v0.6.2. DO NOT EDIT.

package apiservice

import (
	api "GreenFish/server/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *api.QingyuUserRegisterRequest, callOptions ...callopt.Option) (r *api.QingyuUserRegisterResponse, err error)
	Login(ctx context.Context, req *api.QingyuUserLoginRequest, callOptions ...callopt.Option) (r *api.QingyuUserLoginResponse, err error)
	GetUserInfo(ctx context.Context, req *api.QingyuUserRequest, callOptions ...callopt.Option) (r *api.QingyuUserResponse, err error)
	Feed(ctx context.Context, req *api.QingyuFeedRequest, callOptions ...callopt.Option) (r *api.QingyuFeedResponse, err error)
	PublishVideo(ctx context.Context, req *api.QingyuPublishActionRequest, callOptions ...callopt.Option) (r *api.QingyuPublishActionResponse, err error)
	VideoList(ctx context.Context, req *api.QingyuPublishListRequest, callOptions ...callopt.Option) (r *api.QingyuPublishListResponse, err error)
	Favorite(ctx context.Context, req *api.QingyuFavoriteActionRequest, callOptions ...callopt.Option) (r *api.QingyuFavoriteActionResponse, err error)
	FavoriteList(ctx context.Context, req *api.QingyuFavoriteListRequest, callOptions ...callopt.Option) (r *api.QingyuFavoriteListResponse, err error)
	Comment(ctx context.Context, req *api.QingyuCommentActionRequest, callOptions ...callopt.Option) (r *api.QingyuCommentActionResponse, err error)
	CommentList(ctx context.Context, req *api.QingyuCommentListRequest, callOptions ...callopt.Option) (r *api.QingyuCommentListResponse, err error)
	Action(ctx context.Context, req *api.QingyuRelationActionRequest, callOptions ...callopt.Option) (r *api.QingyuRelationActionResponse, err error)
	FollowingList(ctx context.Context, req *api.QingyuRelationFollowListRequest, callOptions ...callopt.Option) (r *api.QingyuRelationFollowListResponse, err error)
	FollowerList(ctx context.Context, req *api.QingyuRelationFollowerListRequest, callOptions ...callopt.Option) (r *api.QingyuRelationFollowerListResponse, err error)
	FriendList(ctx context.Context, req *api.QingyuRelationFriendListRequest, callOptions ...callopt.Option) (r *api.QingyuRelationFriendListResponse, err error)
	ChatHistory(ctx context.Context, req *api.QingyuMessageChatRequest, callOptions ...callopt.Option) (r *api.QingyuMessageChatResponse, err error)
	SentMessage(ctx context.Context, req *api.QingyuMessageActionRequest, callOptions ...callopt.Option) (r *api.QingyuMessageActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kApiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kApiServiceClient struct {
	*kClient
}

func (p *kApiServiceClient) Register(ctx context.Context, req *api.QingyuUserRegisterRequest, callOptions ...callopt.Option) (r *api.QingyuUserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kApiServiceClient) Login(ctx context.Context, req *api.QingyuUserLoginRequest, callOptions ...callopt.Option) (r *api.QingyuUserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kApiServiceClient) GetUserInfo(ctx context.Context, req *api.QingyuUserRequest, callOptions ...callopt.Option) (r *api.QingyuUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kApiServiceClient) Feed(ctx context.Context, req *api.QingyuFeedRequest, callOptions ...callopt.Option) (r *api.QingyuFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kApiServiceClient) PublishVideo(ctx context.Context, req *api.QingyuPublishActionRequest, callOptions ...callopt.Option) (r *api.QingyuPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishVideo(ctx, req)
}

func (p *kApiServiceClient) VideoList(ctx context.Context, req *api.QingyuPublishListRequest, callOptions ...callopt.Option) (r *api.QingyuPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoList(ctx, req)
}

func (p *kApiServiceClient) Favorite(ctx context.Context, req *api.QingyuFavoriteActionRequest, callOptions ...callopt.Option) (r *api.QingyuFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Favorite(ctx, req)
}

func (p *kApiServiceClient) FavoriteList(ctx context.Context, req *api.QingyuFavoriteListRequest, callOptions ...callopt.Option) (r *api.QingyuFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteList(ctx, req)
}

func (p *kApiServiceClient) Comment(ctx context.Context, req *api.QingyuCommentActionRequest, callOptions ...callopt.Option) (r *api.QingyuCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, req)
}

func (p *kApiServiceClient) CommentList(ctx context.Context, req *api.QingyuCommentListRequest, callOptions ...callopt.Option) (r *api.QingyuCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, req)
}

func (p *kApiServiceClient) Action(ctx context.Context, req *api.QingyuRelationActionRequest, callOptions ...callopt.Option) (r *api.QingyuRelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, req)
}

func (p *kApiServiceClient) FollowingList(ctx context.Context, req *api.QingyuRelationFollowListRequest, callOptions ...callopt.Option) (r *api.QingyuRelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowingList(ctx, req)
}

func (p *kApiServiceClient) FollowerList(ctx context.Context, req *api.QingyuRelationFollowerListRequest, callOptions ...callopt.Option) (r *api.QingyuRelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kApiServiceClient) FriendList(ctx context.Context, req *api.QingyuRelationFriendListRequest, callOptions ...callopt.Option) (r *api.QingyuRelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}

func (p *kApiServiceClient) ChatHistory(ctx context.Context, req *api.QingyuMessageChatRequest, callOptions ...callopt.Option) (r *api.QingyuMessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChatHistory(ctx, req)
}

func (p *kApiServiceClient) SentMessage(ctx context.Context, req *api.QingyuMessageActionRequest, callOptions ...callopt.Option) (r *api.QingyuMessageActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SentMessage(ctx, req)
}
