// Code generated by Kitex v0.6.2. DO NOT EDIT.

package interactionserver

import (
	interaction "GreenFish/server/kitex_gen/interaction"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Favorite(ctx context.Context, req *interaction.QingyuFavoriteActionRequest, callOptions ...callopt.Option) (r *interaction.QingyuFavoriteActionResponse, err error)
	GetFavoriteVideoIdList(ctx context.Context, req *interaction.QingyuGetFavoriteVideoIdListRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetFavoriteVideoIdListResponse, err error)
	Comment(ctx context.Context, req *interaction.QingyuCommentActionRequest, callOptions ...callopt.Option) (r *interaction.QingyuCommentActionResponse, err error)
	GetCommentList(ctx context.Context, req *interaction.QingyuGetCommentListRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetCommentListResponse, err error)
	GetVideoInteractInfo(ctx context.Context, req *interaction.QingyuGetVideoInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetVideoInteractInfoResponse, err error)
	BatchGetVideoInteractInfo(ctx context.Context, req *interaction.QingyuBatchGetVideoInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuBatchGetVideoInteractInfoResponse, err error)
	GetUserInteractInfo(ctx context.Context, req *interaction.QingyuGetUserInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetUserInteractInfoResponse, err error)
	BatchGetUserInteractInfo(ctx context.Context, req *interaction.QingyuBatchGetUserInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuBatchGetUserInteractInfoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractionServerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractionServerClient struct {
	*kClient
}

func (p *kInteractionServerClient) Favorite(ctx context.Context, req *interaction.QingyuFavoriteActionRequest, callOptions ...callopt.Option) (r *interaction.QingyuFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Favorite(ctx, req)
}

func (p *kInteractionServerClient) GetFavoriteVideoIdList(ctx context.Context, req *interaction.QingyuGetFavoriteVideoIdListRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetFavoriteVideoIdListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteVideoIdList(ctx, req)
}

func (p *kInteractionServerClient) Comment(ctx context.Context, req *interaction.QingyuCommentActionRequest, callOptions ...callopt.Option) (r *interaction.QingyuCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, req)
}

func (p *kInteractionServerClient) GetCommentList(ctx context.Context, req *interaction.QingyuGetCommentListRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, req)
}

func (p *kInteractionServerClient) GetVideoInteractInfo(ctx context.Context, req *interaction.QingyuGetVideoInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetVideoInteractInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoInteractInfo(ctx, req)
}

func (p *kInteractionServerClient) BatchGetVideoInteractInfo(ctx context.Context, req *interaction.QingyuBatchGetVideoInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuBatchGetVideoInteractInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetVideoInteractInfo(ctx, req)
}

func (p *kInteractionServerClient) GetUserInteractInfo(ctx context.Context, req *interaction.QingyuGetUserInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuGetUserInteractInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInteractInfo(ctx, req)
}

func (p *kInteractionServerClient) BatchGetUserInteractInfo(ctx context.Context, req *interaction.QingyuBatchGetUserInteractInfoRequest, callOptions ...callopt.Option) (r *interaction.QingyuBatchGetUserInteractInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetUserInteractInfo(ctx, req)
}
