apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenfish-interaction-dep
spec:
  selector:
    matchLabels:
      app: greenfish-interaction
  replicas: 1
  template:
    metadata:
      labels:
        app: greenfish-interaction
    spec:
      containers:
        - name: greenfish-interaction
          image: violapioggia/greenfish_interaction
          ports:
            - containerPort: 10003
          volumeMounts:
            - name: greenfish-interaction-data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: greenfish-interaction-data
          hostPath:
            path: /home/violapioggia/greenfish/interaction/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: greenfish-interaction-svc
spec:
  ports:
    - name: greenfish-interaction
      port: 10003
      targetPort: 10003
  selector:
    app: greenfish-interaction
  type: ClusterIP